source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DemoLibrary_Example', :exclusive => true do
  pod 'DemoLibrary', :path => '../'
end

target 'DemoLibrary_Tests', :exclusive => true do
  pod 'DemoLibrary', :path => '../'

  
end
